# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Fri Aug 15 11:20:15 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(494, 362)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 50, 126, 99))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.EXPER_COUNT = QtGui.QSpinBox(self.widget)
        self.EXPER_COUNT.setProperty("value", 1)
        self.EXPER_COUNT.setObjectName(_fromUtf8("EXPER_COUNT"))
        self.gridLayout_3.addWidget(self.EXPER_COUNT, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 2)
        self.PlotGraph = QtGui.QPushButton(self.widget)
        self.PlotGraph.setObjectName(_fromUtf8("PlotGraph"))
        self.gridLayout_3.addWidget(self.PlotGraph, 2, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 211, 218))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SPEED = QtGui.QLineEdit(self.widget1)
        self.SPEED.setObjectName(_fromUtf8("SPEED"))
        self.gridLayout.addWidget(self.SPEED, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.FC = QtGui.QLineEdit(self.widget1)
        self.FC.setObjectName(_fromUtf8("FC"))
        self.gridLayout.addWidget(self.FC, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.N = QtGui.QLineEdit(self.widget1)
        self.N.setObjectName(_fromUtf8("N"))
        self.gridLayout.addWidget(self.N, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.A_NOISE = QtGui.QLineEdit(self.widget1)
        self.A_NOISE.setObjectName(_fromUtf8("A_NOISE"))
        self.gridLayout.addWidget(self.A_NOISE, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.A_SIGNAL = QtGui.QLineEdit(self.widget1)
        self.A_SIGNAL.setObjectName(_fromUtf8("A_SIGNAL"))
        self.gridLayout.addWidget(self.A_SIGNAL, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 0.3)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(260, 210, 152, 53))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.widget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Провести эксперимент", None))
        self.PlotGraph.setText(_translate("MainWindow", "Построить графики", None))
        self.label_8.setText(_translate("MainWindow", "Количество экспериментов", None))
        self.label.setText(_translate("MainWindow", "Частота несущей [Гц]", None))
        self.label_2.setText(_translate("MainWindow", "Количество передающихся символов", None))
        self.label_3.setText(_translate("MainWindow", "Символьная скорость", None))
        self.label_4.setText(_translate("MainWindow", "Амплитуда шума", None))
        self.label_5.setText(_translate("MainWindow", "Амплитуда сигнала", None))
        self.label_6.setText(_translate("MainWindow", "Порог детектирования", None))
        self.label_7.setText(_translate("MainWindow", "Параметры системы", None))
        self.label_10.setText(_translate("MainWindow", "Мат. ожидание", None))
        self.label_12.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "Дисперсия", None))
        self.label_9.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "Результаты", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Fri Aug 15 11:52:56 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(427, 294)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(60, 0, 321, 61))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 50, 126, 99))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.EXPER_COUNT = QtGui.QSpinBox(self.widget)
        self.EXPER_COUNT.setProperty("value", 1)
        self.EXPER_COUNT.setObjectName(_fromUtf8("EXPER_COUNT"))
        self.gridLayout_3.addWidget(self.EXPER_COUNT, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 2)
        self.PlotGraph = QtGui.QPushButton(self.widget)
        self.PlotGraph.setObjectName(_fromUtf8("PlotGraph"))
        self.gridLayout_3.addWidget(self.PlotGraph, 2, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 211, 218))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SPEED = QtGui.QLineEdit(self.widget1)
        self.SPEED.setObjectName(_fromUtf8("SPEED"))
        self.gridLayout.addWidget(self.SPEED, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.FC = QtGui.QLineEdit(self.widget1)
        self.FC.setObjectName(_fromUtf8("FC"))
        self.gridLayout.addWidget(self.FC, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.N = QtGui.QLineEdit(self.widget1)
        self.N.setObjectName(_fromUtf8("N"))
        self.gridLayout.addWidget(self.N, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.A_NOISE = QtGui.QLineEdit(self.widget1)
        self.A_NOISE.setObjectName(_fromUtf8("A_NOISE"))
        self.gridLayout.addWidget(self.A_NOISE, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.A_SIGNAL = QtGui.QLineEdit(self.widget1)
        self.A_SIGNAL.setObjectName(_fromUtf8("A_SIGNAL"))
        self.gridLayout.addWidget(self.A_SIGNAL, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 0.3)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(260, 190, 152, 72))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.widget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_12 = QtGui.QLabel(self.widget2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Моделирование приемо-передающей системы", None))
        self.label_14.setText(_translate("MainWindow", "Амплитудная манипуляция с помехоусточивым кодированим Хемминг(7,4,3)", None))
        self.pushButton.setText(_translate("MainWindow", "Провести эксперимент", None))
        self.PlotGraph.setText(_translate("MainWindow", "Построить графики", None))
        self.label_8.setText(_translate("MainWindow", "Количество экспериментов", None))
        self.label.setText(_translate("MainWindow", "Частота несущей [Гц]", None))
        self.label_2.setText(_translate("MainWindow", "Количество передающихся символов", None))
        self.label_3.setText(_translate("MainWindow", "Символьная скорость", None))
        self.label_4.setText(_translate("MainWindow", "Амплитуда шума", None))
        self.label_5.setText(_translate("MainWindow", "Амплитуда сигнала", None))
        self.label_6.setText(_translate("MainWindow", "Порог детектирования", None))
        self.label_7.setText(_translate("MainWindow", "Параметры системы", None))
        self.label_10.setText(_translate("MainWindow", "Мат. ожидание", None))
        self.label_11.setText(_translate("MainWindow", "Дисперсия", None))
        self.label_9.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "Результаты", None))
        self.label_12.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Fri Aug 15 12:50:00 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(432, 289)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(20, 20, 385, 229))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_14 = QtGui.QLabel(self.splitter_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SPEED = QtGui.QLineEdit(self.widget)
        self.SPEED.setObjectName(_fromUtf8("SPEED"))
        self.gridLayout.addWidget(self.SPEED, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.FC = QtGui.QLineEdit(self.widget)
        self.FC.setFrame(True)
        self.FC.setObjectName(_fromUtf8("FC"))
        self.gridLayout.addWidget(self.FC, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.N = QtGui.QLineEdit(self.widget)
        self.N.setObjectName(_fromUtf8("N"))
        self.gridLayout.addWidget(self.N, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.A_NOISE = QtGui.QLineEdit(self.widget)
        self.A_NOISE.setObjectName(_fromUtf8("A_NOISE"))
        self.gridLayout.addWidget(self.A_NOISE, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.A_SIGNAL = QtGui.QLineEdit(self.widget)
        self.A_SIGNAL.setObjectName(_fromUtf8("A_SIGNAL"))
        self.gridLayout.addWidget(self.A_SIGNAL, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 0.3)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.EXPER_COUNT = QtGui.QSpinBox(self.widget1)
        self.EXPER_COUNT.setProperty("value", 1)
        self.EXPER_COUNT.setObjectName(_fromUtf8("EXPER_COUNT"))
        self.gridLayout_3.addWidget(self.EXPER_COUNT, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.widget1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 2)
        self.PlotGraph = QtGui.QPushButton(self.widget1)
        self.PlotGraph.setObjectName(_fromUtf8("PlotGraph"))
        self.gridLayout_3.addWidget(self.PlotGraph, 2, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.widget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_12 = QtGui.QLabel(self.widget2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Моделирование приемо-передающей системы", None))
        self.label_14.setText(_translate("MainWindow", "Амплитудная манипуляция с помехоусточивым кодированим Хемминг(7,4,3)", None))
        self.SPEED.setText(_translate("MainWindow", "10", None))
        self.label.setText(_translate("MainWindow", "Частота несущей [Гц]", None))
        self.FC.setText(_translate("MainWindow", "10", None))
        self.label_2.setText(_translate("MainWindow", "Количество передающихся символов", None))
        self.N.setText(_translate("MainWindow", "32", None))
        self.label_4.setText(_translate("MainWindow", "Амплитуда шума", None))
        self.A_NOISE.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "Амплитуда сигнала", None))
        self.A_SIGNAL.setText(_translate("MainWindow", "1.25", None))
        self.label_6.setText(_translate("MainWindow", "Порог детектирования", None))
        self.label_7.setText(_translate("MainWindow", "Параметры системы", None))
        self.label_3.setText(_translate("MainWindow", "Символьная скорость", None))
        self.pushButton.setText(_translate("MainWindow", "Провести эксперимент", None))
        self.PlotGraph.setText(_translate("MainWindow", "Построить графики", None))
        self.label_8.setText(_translate("MainWindow", "Количество экспериментов", None))
        self.label_10.setText(_translate("MainWindow", "Мат. ожидание", None))
        self.label_11.setText(_translate("MainWindow", "Дисперсия", None))
        self.label_9.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "Результаты", None))
        self.label_12.setText(_translate("MainWindow", "0", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Fri Aug 15 13:03:22 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(432, 289)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(20, 20, 385, 229))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_14 = QtGui.QLabel(self.splitter_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SPEED = QtGui.QLineEdit(self.widget)
        self.SPEED.setObjectName(_fromUtf8("SPEED"))
        self.gridLayout.addWidget(self.SPEED, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.FC = QtGui.QLineEdit(self.widget)
        self.FC.setFrame(True)
        self.FC.setObjectName(_fromUtf8("FC"))
        self.gridLayout.addWidget(self.FC, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.N = QtGui.QLineEdit(self.widget)
        self.N.setObjectName(_fromUtf8("N"))
        self.gridLayout.addWidget(self.N, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.A_NOISE = QtGui.QLineEdit(self.widget)
        self.A_NOISE.setObjectName(_fromUtf8("A_NOISE"))
        self.gridLayout.addWidget(self.A_NOISE, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.A_SIGNAL = QtGui.QLineEdit(self.widget)
        self.A_SIGNAL.setObjectName(_fromUtf8("A_SIGNAL"))
        self.gridLayout.addWidget(self.A_SIGNAL, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 0.3)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.EXPER_COUNT = QtGui.QSpinBox(self.widget1)
        self.EXPER_COUNT.setProperty("value", 1)
        self.EXPER_COUNT.setObjectName(_fromUtf8("EXPER_COUNT"))
        self.gridLayout_3.addWidget(self.EXPER_COUNT, 0, 1, 1, 1)
        self.CONDUCT_EXPERIMENT = QtGui.QPushButton(self.widget1)
        self.CONDUCT_EXPERIMENT.setObjectName(_fromUtf8("CONDUCT_EXPERIMENT"))
        self.gridLayout_3.addWidget(self.CONDUCT_EXPERIMENT, 1, 0, 1, 2)
        self.PLOT_GRAPH = QtGui.QPushButton(self.widget1)
        self.PLOT_GRAPH.setObjectName(_fromUtf8("PLOT_GRAPH"))
        self.gridLayout_3.addWidget(self.PLOT_GRAPH, 2, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.widget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_12 = QtGui.QLabel(self.widget2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Моделирование приемо-передающей системы", None))
        self.label_14.setText(_translate("MainWindow", "Амплитудная манипуляция с помехоусточивым кодированим Хемминг(7,4,3)", None))
        self.SPEED.setText(_translate("MainWindow", "10", None))
        self.label.setText(_translate("MainWindow", "Частота несущей [Гц]", None))
        self.FC.setText(_translate("MainWindow", "10", None))
        self.label_2.setText(_translate("MainWindow", "Количество передающихся символов", None))
        self.N.setText(_translate("MainWindow", "32", None))
        self.label_4.setText(_translate("MainWindow", "Амплитуда шума", None))
        self.A_NOISE.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "Амплитуда сигнала", None))
        self.A_SIGNAL.setText(_translate("MainWindow", "1.25", None))
        self.label_6.setText(_translate("MainWindow", "Порог детектирования", None))
        self.label_7.setText(_translate("MainWindow", "Параметры системы", None))
        self.label_3.setText(_translate("MainWindow", "Символьная скорость", None))
        self.CONDUCT_EXPERIMENT.setText(_translate("MainWindow", "Провести эксперимент", None))
        self.PLOT_GRAPH.setText(_translate("MainWindow", "Построить графики", None))
        self.label_8.setText(_translate("MainWindow", "Количество экспериментов", None))
        self.label_10.setText(_translate("MainWindow", "Мат. ожидание", None))
        self.label_11.setText(_translate("MainWindow", "Дисперсия", None))
        self.label_9.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "Результаты", None))
        self.label_12.setText(_translate("MainWindow", "0", None))

